spring:
  application:
    name: organization-service

  # ------------------------------------------------------------------
  # DATABASE — Liquibase
  # ------------------------------------------------------------------
  liquibase:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME:yowyob}
    user: ${DB_LIQUIBASE_USERNAME}
    password: ${DB_LIQUIBASE_PASSWORD}
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: ride_and_go
    liquibase-schema: ride_and_go

  # ------------------------------------------------------------------
  # DATABASE — R2DBC réactif
  # ------------------------------------------------------------------
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME:yowyob}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
      validation-query: SELECT 1

  sql:
    init:
      mode: never

  # ------------------------------------------------------------------
  # REDIS CLUSTER
  # ------------------------------------------------------------------
  data:
    redis:
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      cluster:
        nodes:
          - ${REDIS_HOST}:7001
          - ${REDIS_HOST}:7002
          - ${REDIS_HOST}:7003
          - ${REDIS_HOST}:7004
          - ${REDIS_HOST}:7005
          - ${REDIS_HOST}:7006
        max-redirects: 3
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 2
        cluster:
          refresh:
            adaptive: true
            period: 30s
            dynamic-refresh-sources: false

  # --- KAFKA PROD ---
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT:29092}

    # ── Authentification SASL/SCRAM-SHA-256 ────────────────────────
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config: >
        org.apache.kafka.common.security.scram.ScramLoginModule required
        username="${KAFKA_BACKEND_USER}"
        password="${KAFKA_BACKEND_PASSWORD}";
        
    consumer:
      group-id: organisation-group-prod
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


application:
  cors:
    # Autorise ton propre domaine pour que Swagger UI (JS) puisse appeler l'API
    allowed-origins: "https://organization-service.pynfi.com"